/**
 * 
 * @authors Your Name (you@example.org)
 * @date    2016-06-25 23:19:39
 * @version $Id$
 */
//异步加载需要的图片路径数据
 var data={
 	nav-c-b:["images/nav-c-b-l-1.jpg", "images/nav-c-b-l-em.png", "images/nav-c-b-l-2.jpg", "images/nav-c-b-l-em.png", "images/nav-c-b-l-3.jpg", "images/nav-c-b-l-em.png", "images/nav-c-b-l-4.jpg", "images/nav-c-b-l-em.png", "images/nav-c-b-l-5.jpg", "images/nav-c-b-l-em.png", "images/nav-c-b-r-1.jpg", "images/nav-c-b-r-app-1.jpg", "images/nav-c-b-r-2.jpg", "images/nav-c-b-r-app-2.jpg", "images/nav-c-b-r-3.jpg", "images/nav-c-b-r-app-3.jpg", "images/nav-c-b-r-4.jpg", "images/nav-c-b-r-app-4.jpg", "images/nav-c-b-r-5.jpg", "images/nav-c-b-r-app-5.jpg", "images/nav-c-b-r-6.jpg", "images/nav-c-b-r-app-6.jpg", "images/nav-c-b-r-7.jpg", "images/nav-c-b-r-app-7.jpg", "images/nav-c-b-r-8.jpg", "images/nav-c-b-r-app-8.jpg", "images/nav-c-b-r-9.jpg", "images/nav-c-b-r-app-9.jpg", "images/nav-c-b-r-10.jpg", "images/nav-c-b-r-app-10.jpg"],

    content-l-1:["images/content-l-h-1.png", "images/TB-index-275.jpg", "images/TB-index-63.jpg", "images/TB-index-271.jpg", "images/TB-index-37.jpg", "images/TB-index-255.jpg", "images/TB-index-64.jpg", "images/TB-index-237.jpg", "images/TB-index-282.jpg", "images/TB-index-275.jpg", "images/TB-index-63.jpg", "images/TB-index-271.jpg", "images/TB-index-37.jpg", "images/TB-index-255.jpg", "images/TB-index-64.jpg", "images/TB-index-237.jpg", "images/TB-index-282.jpg", "images/TB-index-275.jpg", "images/TB-index-63.jpg", "images/TB-index-271.jpg", "images/TB-index-37.jpg", "images/TB-index-255.jpg", "images/TB-index-64.jpg", "images/TB-index-237.jpg", "images/TB-index-282.jpg", "images/TB-index-275.jpg", "images/TB-index-63.jpg", "images/TB-index-271.jpg", "images/TB-index-37.jpg", "images/TB-index-255.jpg", "images/TB-index-64.jpg", "images/TB-index-237.jpg", "images/TB-index-282.jpg"],
    content-r-1:["images/TB-index-210.jpg", "images/TB-index-112.jpg", "images/TB-index-257.jpg", "images/TB-index-300.jpg", "images/TB-index-286.jpg", "images/TB-index-210.jpg"],

    content-r-2:["images/TB-index-210.jpg", "images/TB-index-112.jpg", "images/TB-index-257.jpg", "images/TB-index-300.jpg", "images/TB-index-286.jpg", "images/TB-index-210.jpg", "images/TB-index-112.jpg", "images/TB-index-257.jpg", "images/TB-index-300.jpg", "images/TB-index-286.jpg"],
    content-l-2:["images/content-l-ad.jpg","images/content-l-h-2.png", "images/TB-index-40.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-233.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-71.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-69.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg"],
    
    content-r-3:["images/TB-index-210.jpg", "images/TB-index-112.jpg", "images/TB-index-257.jpg", "images/TB-index-300.jpg"],
    content-l-3:["images/content-l-h-3.png", "images/TB-index-55.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-46.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-77.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-29.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-129.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-269.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-116.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-217.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg"],
    
    content-r-4:["images/TB-index-107.jpg"],
    content-l-4:["images/content-l-h-4.png", "images/TB-index-164.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-59.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-137.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-133.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-140.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-103.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-28.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg", "images/TB-index-45.jpg", "images/TB-index-248.jpg", "images/TB-index-86.jpg", "images/TB-index-70.jpg"],

    content-l-5:["images/content-l-h-5.png", "images/TB-index-55.jpg", "images/TB-index-318.jpg", "images/TB-index-256.jpg", "images/TB-index-159.jpg", "images/TB-index-256.jpg", "images/TB-index-159.jpg", "images/TB-index-256.jpg", "images/TB-index-159.jpg", "images/TB-index-55.jpg", "images/TB-index-318.jpg", "images/TB-index-256.jpg", "images/TB-index-159.jpg", "images/TB-index-256.jpg", "images/TB-index-159.jpg", "images/TB-index-256.jpg", "images/TB-index-159.jpg"],

    content-cont-1:["images/content-cont-1-h.png", "images/TB-index-117.jpg", "images/TB-index-333.jpg", "images/TB-index-317.jpg", "images/TB-index-117.jpg", "images/TB-index-333.jpg", "images/TB-index-317.jpg", "images/TB-index-117.jpg", "images/TB-index-333.jpg", "images/TB-index-317.jpg", "images/TB-index-50.jpg", "images/TB-index-114.jpg", "images/TB-index-13.jpg"],
     
    content-cont-2:["images/content-cont-2-h.png", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg", "images/TB-index-117.jpg"]
 }
